In [6]:
import numpy as np

uv = np.zeros((108, 100))

for j in range(4):
    for i in range(4):
        start_row = i * 22 + 10
        start_col = j * 20 + 10
        value = i + j * 4
        uv[start_row:start_row+22, start_col:start_col+20] = value

print(uv)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
